"""Safe local storage for uploaded resume PDFs."""
from pathlib import Path
from uuid import uuid4

from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename


PDF_SIGNATURE = b"%PDF-"


def validate_resume_file(upload: FileStorage) -> str | None:
    """Return a client-safe validation error, or None for a valid PDF."""
    if upload is None or not upload.filename:
        return "A PDF file is required in the 'file' form field"
    safe_name = secure_filename(upload.filename)
    if not safe_name or Path(safe_name).suffix.lower() != ".pdf":
        return "Only .pdf files are allowed"
    signature = upload.stream.read(5)
    upload.stream.seek(0)
    if signature != PDF_SIGNATURE:
        return "Uploaded file is not a valid PDF"
    return None


def save_resume_file(upload: FileStorage, upload_folder: str) -> tuple[str, str, int]:
    """Store a validated file under a UUID name, never its user-provided name."""
    original_filename = secure_filename(upload.filename)
    stored_filename = f"{uuid4().hex}.pdf"
    target_folder = Path(upload_folder)
    target_folder.mkdir(parents=True, exist_ok=True)
    target_path = target_folder / stored_filename
    upload.save(target_path)
    return original_filename, stored_filename, target_path.stat().st_size


def delete_resume_file(upload_folder: str, stored_filename: str) -> None:
    """Remove only the UUID filename previously generated by this application."""
    (Path(upload_folder) / stored_filename).unlink(missing_ok=True)
